# Generated by Django 2.2.5 on 2019-10-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50, null=True)),
                ('aquisition_date', models.DateField(null=True)),
                ('warranty_expiry_date', models.DateField(blank=True, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('legal_entity', models.CharField(blank=True, max_length=100)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('host_name', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'State',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitted_locations', models.ManyToManyField(to='assets_app.Location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('change_details', models.TextField(editable=False)),
                ('asset', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets_app.Asset')),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=models.SET('USER DELETED'), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Change',
                'verbose_name_plural': 'Changes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('selectable', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('mptt_level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets_app.Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=models.SET('UNCATEGORISED'), to='assets_app.Category'),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(null=True, on_delete=models.SET('NOT SET'), to='assets_app.Location'),
        ),
        migrations.AddField(
            model_name='asset',
            name='state',
            field=models.ForeignKey(null=True, on_delete=models.SET('NOT SET'), to='assets_app.State'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=models.SET('NOT SET'), to='assets_app.Vendor'),
        ),
    ]
