# Generated by Django 2.2.5 on 2019-09-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='level',
            new_name='mptt_level',
        ),
    ]
