# Generated by Django 2.2.5 on 2019-09-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='selectable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
