# Generated by Django 2.2.5 on 2019-09-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0004_location_selectable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='selectable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
