# Generated by Django 2.2.5 on 2019-09-29 07:41

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0006_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=50)),
                ('category', mptt.fields.TreeForeignKey(on_delete=models.SET('UNCATEGORISED'), to='assets_app.Category')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
