# Generated by Django 2.2.5 on 2019-09-29 12:50

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0007_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=models.SET('NOT SET'), to='assets_app.Location'),
        ),
    ]
