# Generated by Django 2.2.5 on 2019-09-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0008_asset_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
