# Generated by Django 2.2.5 on 2019-09-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0009_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=models.SET('NOT SET'), to='assets_app.Vendor'),
        ),
    ]
