# Generated by Django 2.2.5 on 2019-09-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0011_asset_aquisition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='added_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry_date',
            field=models.DateField(null=True),
        ),
    ]
