# Generated by Django 2.2.5 on 2019-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0012_auto_20190929_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='host_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='legal_entity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='modified_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
