# Generated by Django 2.2.5 on 2019-09-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0013_auto_20190929_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='warranty_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
