# Generated by Django 2.2.5 on 2019-09-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0014_auto_20190929_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(editable=False, null=True)),
                ('change_details', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_app.Asset')),
            ],
            options={
                'verbose_name': 'Change',
                'verbose_name_plural': 'Changes',
            },
        ),
    ]
