# Generated by Django 2.2.5 on 2019-09-29 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0015_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='change',
            name='asset',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='assets_app.Asset'),
        ),
        migrations.AlterField(
            model_name='change',
            name='change_details',
            field=models.TextField(editable=False),
        ),
    ]
