# Generated by Django 2.2.5 on 2019-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0016_auto_20190929_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='state',
            field=models.ForeignKey(null=True, on_delete=models.SET('NOT SET'), to='assets_app.State'),
        ),
    ]
