# Generated by Django 2.2.5 on 2019-10-03 05:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_app', '0017_asset_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='author',
            field=models.ForeignKey(editable=False, null=True, on_delete=models.SET('USER DELETED'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 5, 3, 4, 365170, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 5, 3, 4, 365170, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='change',
            name='asset',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets_app.Asset'),
        ),
        migrations.AlterField(
            model_name='change',
            name='changed_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 5, 3, 4, 366163, tzinfo=utc), editable=False),
        ),
    ]
