# Generated by Django 2.2.5 on 2019-10-09 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assets_app', '0018_auto_20191003_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='modified_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='change',
            name='changed_on',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
